trigger:
- '*'

pool:
  name: Default # Replace Default with the name of your agent pool if you used a different pool

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET SDK 6.x'
  inputs:
    packageType: sdk
    version: '6.x'

- task: NodeTool@0
  displayName: 'Node Tool'
  inputs:
    versionSpec: '12.x'

- task: Npm@1
  displayName: 'Run npm install'
  inputs:
    # command: 'install'
    verbose: false
    # customCommand: 'install --force'

# - script: './node_modules/.bin/node-sass Tailspin.SpaceGame.Web/wwwroot --output Tailspin.SpaceGame.Web/wwwroot'
#   displayName: 'Compile Sass assets'

# - script: 'D:\Learnings\DevOpsProjects\vsts-agent-win-x64-3.245.0\_work\1\s\node_modules\.bin\node-sass Tailspin.SpaceGame.Web/wwwroot --output Tailspin.SpaceGame.Web/wwwroot'
#   displayName: 'Compile Sass assets'
- script: npx node-sass Tailspin.SpaceGame.Web/wwwroot --output Tailspin.SpaceGame.Web/wwwroot
  displayName: 'Compile Sass assets'


# - task: gulp@1
#   displayName: 'Run gulp tasks'
- task: Npm@1
  displayName: 'Install Gulp CLI Globally'
  inputs:
    command: custom
    customCommand: 'install -g gulp-cli'
    workingDir: '$(Build.SourcesDirectory)'
    verbose: false

- script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
  displayName: 'Write build info'
  workingDirectory: Tailspin.SpaceGame.Web/wwwroot

- task: DotNetCoreCLI@2
  displayName: 'Restore project dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build the project - Release'
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration Release'
    projects: '**/*.csproj'